source 'https://rubygems.org'

gem 'rails', '3.2.17'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'carrierwave', '0.9.0'

gem 'rmagick'

gem 'ransack'

gem 'haml-rails'

gem 'devise' 
# Includes bcrypt

gem 'cancan'

gem 'acts-as-taggable-on', '~> 2.4.1'

gem "fog", "~> 1.3.1"

gem 'acts_as_votable', '~> 0.9.0'

gem "acts_as_follower"

gem 'will_paginate', '~> 3.0'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'hirb'
  gem 'sextant'
  gem 'letter_opener'
end